vich_uploader:
    db_driver: orm
    mappings:
        media:
            uri_prefix: /upload/images
            upload_destination: '%kernel.project_dir%/public%app.path.upload.media%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
